substitutions:
  device_name: !secret device_name
  name: !secret name
  min_height: !secret min_height # Min height + 0.1
  max_height: !secret max_height # Max height - 0.1

esphome:
  name: ${device_name}
  comment: ${name}
  platform: ESP8266
  board: nodemcuv2
  includes:
    - src/loctek_height_sensor.h
    - src/uplift_height_sensor.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Home Assistant API
api:
  password: !secret api_password

# Support OTA updates
ota:
  safe_mode: true
  password: !secret api_password

logger:
  level: INFO
  baud_rate: 9600

i2c:

pcf8574:
  - id: "pcf8574_hub"
    address: 0x20
    pcf8575: false
