substitutions:
  device_name: Desk
  name: desk

esphome:
  name: ${name}
  comment: ${device_name}
  platform: ESP8266
  board: nodemcuv2
  includes:
    - src/desk_height_sensor.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: desk_uart
  baud_rate: 9600
  tx_pin: D8
  rx_pin: D7

i2c:

pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: false

sensor:
  - platform: custom
    lambda: |-
      auto desk_height_sensor = new DeskHeightSensor(id(desk_uart));
      App.register_component(desk_height_sensor);
      return {desk_height_sensor};
    sensors:
      id: "desk_height"
      name: Desk Height
      unit_of_measurement: mm
      accuracy_decimals: 0
      icon: "mdi:counter"

# Enable logging
logger:
  level: INFO
  baud_rate: 9600

mqtt:
  broker: !secret mqtt_server
  log_topic: desk/logs

output:
  - platform: gpio
    id: lower_output
    pin:
      pcf8574: pcf8574_hub
      number: 0
      mode:
        output: true
      inverted: true
  - platform: gpio
    id: raise_output
    pin:
      pcf8574: pcf8574_hub
      number: 1
      mode:
        output: true
      inverted: true
  - platform: gpio
    id: memory_key_output
    pin:
      pcf8574: pcf8574_hub
      number: 2
      mode:
        output: true
      inverted: true

switch:
  - platform: template
    name: Raise
    id: raise_switch
    turn_on_action:
      - switch.turn_off: lower_switch
      - switch.turn_off: memory_1_switch
      - switch.turn_off: memory_2_switch
      - switch.turn_off: memory_3_switch
      - switch.turn_off: memory_4_switch
      - output.turn_on: raise_output
      - switch.template.publish:
          id: raise_switch
          state: true
    turn_off_action:
      - output.turn_off: raise_output
      - switch.template.publish:
          id: raise_switch
          state: false
  - platform: template
    name: Lower
    id: lower_switch
    turn_on_action:
      - switch.turn_off: raise_switch
      - switch.turn_off: memory_1_switch
      - switch.turn_off: memory_2_switch
      - switch.turn_off: memory_3_switch
      - switch.turn_off: memory_4_switch
      - output.turn_on: lower_output
      - switch.template.publish:
          id: lower_switch
          state: true
    turn_off_action:
      - output.turn_off: lower_output
      - switch.template.publish:
          id: lower_switch
          state: false
  - platform: template
    name: Memory 1
    id: memory_1_switch
    turn_on_action:
      - switch.turn_off: raise_switch
      - switch.turn_off: lower_switch
      - switch.turn_off: memory_2_switch
      - switch.turn_off: memory_3_switch
      - switch.turn_off: memory_4_switch
      - output.turn_on: raise_output
      - output.turn_on: lower_output
      - switch.template.publish:
          id: memory_1_switch
          state: true
      - delay: 500ms
      - switch.turn_off: memory_1_switch
    turn_off_action:
      - output.turn_off: raise_output
      - output.turn_off: lower_output
      - switch.template.publish:
          id: memory_1_switch
          state: false
  - platform: template
    name: Memory 2
    id: memory_2_switch
    turn_on_action:
      - switch.turn_off: raise_switch
      - switch.turn_off: lower_switch
      - switch.turn_off: memory_1_switch
      - switch.turn_off: memory_3_switch
      - switch.turn_off: memory_4_switch
      - output.turn_on: memory_key_output
      - switch.template.publish:
          id: memory_2_switch
          state: true
      - delay: 500ms
      - switch.turn_off: memory_2_switch
    turn_off_action:
      - output.turn_off: memory_key_output
      - switch.template.publish:
          id: memory_2_switch
          state: false
  - platform: template
    name: Memory 3
    id: memory_3_switch
    turn_on_action:
      - switch.turn_off: raise_switch
      - switch.turn_off: lower_switch
      - switch.turn_off: memory_1_switch
      - switch.turn_off: memory_2_switch
      - switch.turn_off: memory_4_switch
      - output.turn_on: memory_key_output
      - output.turn_on: lower_output
      - switch.template.publish:
          id: memory_3_switch
          state: true
      - delay: 500ms
      - switch.turn_off: memory_3_switch
    turn_off_action:
      - output.turn_off: memory_key_output
      - output.turn_off: lower_output
      - switch.template.publish:
          id: memory_3_switch
          state: false
  - platform: template
    name: Memory 4
    id: memory_4_switch
    turn_on_action:
      - switch.turn_off: raise_switch
      - switch.turn_off: lower_switch
      - switch.turn_off: memory_1_switch
      - switch.turn_off: memory_2_switch
      - switch.turn_off: memory_3_switch
      - output.turn_on: memory_key_output
      - output.turn_on: raise_output
      - switch.template.publish:
          id: memory_4_switch
          state: true
      - delay: 500ms
      - switch.turn_off: memory_4_switch
    turn_off_action:
      - output.turn_off: memory_key_output
      - output.turn_off: raise_output
      - switch.template.publish:
          id: memory_4_switch
          state: false
