<<: !include common.yaml

uart:
  - id: desk_uart
    baud_rate: 9600
    tx_pin: D8
    rx_pin: D5

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: Uptime

  - platform: custom
    lambda: |-
      auto loctek_height_sensor = new LoctekHeightSensor(id(desk_uart));
      App.register_component(loctek_height_sensor);
      return {loctek_height_sensor};
    sensors:
      id: "desk_height"
      name: Desk Height
      unit_of_measurement: cm
      accuracy_decimals: 1
      icon: "mdi:counter"
