<<: !include common.yaml

uart:
  id: desk_uart
  baud_rate: 9600
  tx_pin: D8
  rx_pin: D6

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: Uptime

  - platform: custom
    lambda: |-
      auto uplift_height_sensor = new UpliftHeightSensor(id(desk_uart));
      App.register_component(uplift_height_sensor);
      return {uplift_height_sensor};
    sensors:
      id: "desk_height"
      name: Desk Height
      unit_of_measurement: mm
      accuracy_decimals: 0
      icon: "mdi:counter"
